# Generated by Django 5.2.17 on 2026-08-15 16:09

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorValidation',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('who', models.CharField(max_length=512)),
                ('intent', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_validation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'creator validation',
                'db_table': 'hosted_creator_validations',
                'ordering': ['-created'],
            },
        ),
    ]
