# Mass-upload guards for a collection (see the COLLECTION_* thresholds in
# config/settings/base.py). Two independent counters — things and invitees —
# each with its own fire-once alarm flag, plus one `capacity_unblocked`
# override that a superuser ticks in the admin to lift BOTH ceilings after a
# manual review. All three are inert on a deployment that sets no thresholds,
# which is the standalone default. Three BooleanFields with defaults — no
# backfill, safe on existing rows.
# Generated by Django 5.2.16 on 2026-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_remove_share_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='capacity_unblocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='invites_alarm_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='things_alarm_sent',
            field=models.BooleanField(default=False),
        ),
    ]
