# Generated by Django 5.2.16 on 2026-08-06 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_collection_capacity_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='digest_muted',
            field=models.ManyToManyField(blank=True, db_table='collection_digest_muted', related_name='muted_digest_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
