# Generated by Django 5.2.16 on 2026-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_collection_digest_muted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notify_news',
            field=models.BooleanField(default=True),
        ),
    ]
