# Generated by Django 5.2.16 on 2026-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_subscribe_existing_users_to_digests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='digest_frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=7),
        ),
    ]
