# Generated by Django 5.2.16 on 2026-08-06 17:01

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_collection_digest_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationProposal',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_proposals', to='core.collection')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation_proposals',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('collection', 'email'), name='unique_pending_proposal_per_email')],
            },
        ),
    ]
