# Generated by Django 5.2.16 on 2026-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_invitationproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allow_member_proposals',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='type',
            field=models.CharField(choices=[('BROADCAST', 'Broadcast'), ('COLLECTION_DELETED', 'Collection Deleted'), ('COLLECTION_REVOKED', 'Collection Revoked'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_REQUESTED', 'Booking Requested'), ('FAQ_QUESTION', 'Faq Question'), ('FAQ_ANSWERED', 'Faq Answered'), ('FAQ_HIDDEN', 'Faq Hidden'), ('INVITE_REJECTED', 'Invite Rejected'), ('MEMBER_LEFT', 'Member Left'), ('THING_REPORTED', 'Thing Reported'), ('INVITE_PROPOSED', 'Invite Proposed'), ('INVITE_PROPOSAL_DECLINED', 'Invite Proposal Declined')], max_length=32),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='action',
            field=models.CharField(choices=[('MAGIC_LINK', 'Magic Link'), ('COLLECTION_INVITE', 'Collection Invite'), ('COLLECTION_REJECT', 'Collection Reject'), ('BOOKING_ACCEPT', 'Booking Accept'), ('BOOKING_REJECT', 'Booking Reject'), ('ACCOUNT_DELETE', 'Account Delete'), ('PROPOSAL_APPROVE', 'Invitation Proposal Approve'), ('PROPOSAL_REJECT', 'Invitation Proposal Reject')], db_index=True, default='MAGIC_LINK', max_length=20),
        ),
    ]
