# Generated by Django 5.2.16 on 2026-08-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_collection_allow_member_proposals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='type',
            field=models.CharField(choices=[('BROADCAST', 'Broadcast'), ('COLLECTION_DELETED', 'Collection Deleted'), ('COLLECTION_REVOKED', 'Collection Revoked'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_REQUESTED', 'Booking Requested'), ('FAQ_QUESTION', 'Faq Question'), ('FAQ_ANSWERED', 'Faq Answered'), ('FAQ_HIDDEN', 'Faq Hidden'), ('INVITE_REJECTED', 'Invite Rejected'), ('MEMBER_LEFT', 'Member Left'), ('THING_REPORTED', 'Thing Reported'), ('INVITE_PROPOSED', 'Invite Proposed'), ('INVITE_PROPOSAL_APPROVED', 'Invite Proposal Approved'), ('INVITE_PROPOSAL_DECLINED', 'Invite Proposal Declined')], max_length=32),
        ),
    ]
