# Generated by Django 5.2.16 on 2026-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_inappnotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingtransfer',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
    ]
