# Generated by Django 5.2.16 on 2026-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_thingtransfer_auto_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, choices=[('INVITE', 'Invite'), ('RECOMMENDATION', 'Recommendation'), ('SHARE', 'Share'), ('PUBLIC', 'Public'), ('ONBOARDING', 'Onboarding')], default='', max_length=14),
        ),
    ]
