# Generated by Django 5.2.17 on 2026-08-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='deposit_policy',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='thing',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
