# Generated by Django 5.2.17 on 2026-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_collection_deposit_policy_thing_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiod',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
