# Generated by Django 5.2.17 on 2026-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_bookingperiod_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactivity_notified',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
