# Generated by Django 5.2.17 on 2026-09-07 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_storage_key_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='co_owners',
            field=models.ManyToManyField(blank=True, db_table='collection_co_owners', related_name='co_owned_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
