# Generated by Django 5.2.17 on 2026-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_notification_co_owner_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingperiod',
            name='project_note',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='collection',
            name='reservation_max_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='type',
            field=models.CharField(choices=[('BROADCAST', 'Broadcast'), ('COLLECTION_DELETED', 'Collection Deleted'), ('COLLECTION_REVOKED', 'Collection Revoked'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_REQUESTED', 'Booking Requested'), ('FAQ_QUESTION', 'Faq Question'), ('FAQ_ANSWERED', 'Faq Answered'), ('FAQ_HIDDEN', 'Faq Hidden'), ('INVITE_REJECTED', 'Invite Rejected'), ('MEMBER_LEFT', 'Member Left'), ('THING_REPORTED', 'Thing Reported'), ('INVITE_PROPOSED', 'Invite Proposed'), ('INVITE_PROPOSAL_APPROVED', 'Invite Proposal Approved'), ('INVITE_PROPOSAL_DECLINED', 'Invite Proposal Declined'), ('PROMOTED_CO_OWNER', 'Promoted Co Owner'), ('DEMOTED_CO_OWNER', 'Demoted Co Owner'), ('RESERVATION_MADE', 'Reservation Made'), ('RESERVATION_CANCELLED', 'Reservation Cancelled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='thing',
            name='location',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='thing',
            name='type',
            field=models.CharField(choices=[('GIFT_THING', 'Gift Thing'), ('SELL_THING', 'Sell Thing'), ('RENT_THING', 'Rent Thing'), ('LEND_THING', 'Lend Thing'), ('RESERVE_THING', 'Reserve Thing')], default='GIFT_THING', max_length=16),
        ),
    ]
