# Generated by Django 5.2.17 on 2026-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_reserve_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='reservation_horizon_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
    ]
