# Generated by Django 5.2.17 on 2026-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_collection_reservation_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
