# Generated by Django 5.2.17 on 2026-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_description_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='closed_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
