# Generated by Django 5.2.17 on 2026-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_collection_closed_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='home_page',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
    ]
