# Generated by Django 5.2.17 on 2026-09-10 06:57

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_collection_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarExportMark',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_export_marks', to='core.bookingperiod')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_export_marks', to='core.collection')),
            ],
            options={
                'db_table': 'calendar_export_marks',
                'constraints': [models.UniqueConstraint(fields=('collection', 'booking'), name='uniq_calendar_export_collection_booking')],
            },
        ),
    ]
