# Generated by Django 5.2.17 on 2026-09-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0145_calendarexportmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="reservation_max_active_per_member",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
