# Generated by Django 5.2.17 on 2026-09-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0146_reservation_max_active_per_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="opening_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="collection",
            name="reservation_max_hours",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="collection",
            name="reservation_unit",
            field=models.CharField(
                choices=[("DAY", "Day"), ("HOUR", "Hour")], default="DAY", max_length=4
            ),
        ),
    ]
