# Generated by Django 5.2.17 on 2026-09-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0147_hourly_reservations_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="request_info",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
