# Generated by Django 5.2.17 on 2026-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0148_collection_request_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="request_info",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
    ]
