# Generated by Django 5.2.17 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_drop_reservation_max_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='type',
            field=models.CharField(choices=[('BROADCAST', 'Broadcast'), ('COLLECTION_DELETED', 'Collection Deleted'), ('COLLECTION_REVOKED', 'Collection Revoked'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_REQUESTED', 'Booking Requested'), ('FAQ_QUESTION', 'Faq Question'), ('FAQ_ANSWERED', 'Faq Answered'), ('FAQ_HIDDEN', 'Faq Hidden'), ('INVITE_REJECTED', 'Invite Rejected'), ('MEMBER_LEFT', 'Member Left'), ('THING_REPORTED', 'Thing Reported'), ('INVITE_PROPOSED', 'Invite Proposed'), ('INVITE_PROPOSAL_APPROVED', 'Invite Proposal Approved'), ('INVITE_PROPOSAL_DECLINED', 'Invite Proposal Declined'), ('PROMOTED_CO_OWNER', 'Promoted Co Owner'), ('DEMOTED_CO_OWNER', 'Demoted Co Owner'), ('RESERVATION_MADE', 'Reservation Made'), ('RESERVATION_CANCELLED', 'Reservation Cancelled'), ('BOOKING_DECIDED', 'Booking Decided')], max_length=32),
        ),
    ]
