# Generated by Django 5.2.17 on 2026-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_booking_decided_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='allow_member_proposals',
            field=models.BooleanField(default=False),
        ),
    ]
